/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 77
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_content_token1 = 1,
  aux_sym_content_token2 = 2,
  sym_comment = 3,
  anon_sym_LBRACK_PERCENT = 4,
  anon_sym_PERCENT_RBRACK = 5,
  anon_sym_IF = 6,
  anon_sym_ELSIF = 7,
  anon_sym_ELSE = 8,
  anon_sym_END = 9,
  anon_sym_EQ = 10,
  anon_sym_PIPE = 11,
  anon_sym_SQUOTE = 12,
  aux_sym_string_token1 = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  anon_sym_LBRACE = 16,
  anon_sym_RBRACE = 17,
  anon_sym_DOT = 18,
  sym_identifier = 19,
  sym_bare_string = 20,
  sym_comparison_operator = 21,
  sym_logical_operator = 22,
  sym_source_file = 23,
  sym__statement = 24,
  sym_content = 25,
  sym_directive = 26,
  sym_simple_directive = 27,
  sym_if_block = 28,
  sym_if_directive = 29,
  sym_elsif_directive = 30,
  sym_else_directive = 31,
  sym_end_directive = 32,
  sym__expression = 33,
  sym_binary_expression = 34,
  sym_assignment_expression = 35,
  sym_filter_expression = 36,
  sym_string = 37,
  sym_array = 38,
  sym_hash = 39,
  sym_variable = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym_if_block_repeat1 = 42,
  aux_sym_variable_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_content_token1] = "content_token1",
  [aux_sym_content_token2] = "content_token2",
  [sym_comment] = "comment",
  [anon_sym_LBRACK_PERCENT] = "[%",
  [anon_sym_PERCENT_RBRACK] = "%]",
  [anon_sym_IF] = "IF",
  [anon_sym_ELSIF] = "ELSIF",
  [anon_sym_ELSE] = "ELSE",
  [anon_sym_END] = "END",
  [anon_sym_EQ] = "=",
  [anon_sym_PIPE] = "|",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DOT] = ".",
  [sym_identifier] = "identifier",
  [sym_bare_string] = "bare_string",
  [sym_comparison_operator] = "comparison_operator",
  [sym_logical_operator] = "logical_operator",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_content] = "content",
  [sym_directive] = "directive",
  [sym_simple_directive] = "simple_directive",
  [sym_if_block] = "if_block",
  [sym_if_directive] = "if_directive",
  [sym_elsif_directive] = "elsif_directive",
  [sym_else_directive] = "else_directive",
  [sym_end_directive] = "end_directive",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_assignment_expression] = "assignment_expression",
  [sym_filter_expression] = "filter_expression",
  [sym_string] = "string",
  [sym_array] = "array",
  [sym_hash] = "hash",
  [sym_variable] = "variable",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_if_block_repeat1] = "if_block_repeat1",
  [aux_sym_variable_repeat1] = "variable_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_content_token1] = aux_sym_content_token1,
  [aux_sym_content_token2] = aux_sym_content_token2,
  [sym_comment] = sym_comment,
  [anon_sym_LBRACK_PERCENT] = anon_sym_LBRACK_PERCENT,
  [anon_sym_PERCENT_RBRACK] = anon_sym_PERCENT_RBRACK,
  [anon_sym_IF] = anon_sym_IF,
  [anon_sym_ELSIF] = anon_sym_ELSIF,
  [anon_sym_ELSE] = anon_sym_ELSE,
  [anon_sym_END] = anon_sym_END,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_identifier] = sym_identifier,
  [sym_bare_string] = sym_bare_string,
  [sym_comparison_operator] = sym_comparison_operator,
  [sym_logical_operator] = sym_logical_operator,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_content] = sym_content,
  [sym_directive] = sym_directive,
  [sym_simple_directive] = sym_simple_directive,
  [sym_if_block] = sym_if_block,
  [sym_if_directive] = sym_if_directive,
  [sym_elsif_directive] = sym_elsif_directive,
  [sym_else_directive] = sym_else_directive,
  [sym_end_directive] = sym_end_directive,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_assignment_expression] = sym_assignment_expression,
  [sym_filter_expression] = sym_filter_expression,
  [sym_string] = sym_string,
  [sym_array] = sym_array,
  [sym_hash] = sym_hash,
  [sym_variable] = sym_variable,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_if_block_repeat1] = aux_sym_if_block_repeat1,
  [aux_sym_variable_repeat1] = aux_sym_variable_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_IF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ELSIF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ELSE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_bare_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_logical_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_if_block] = {
    .visible = true,
    .named = true,
  },
  [sym_if_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_elsif_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_else_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_end_directive] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_filter_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_hash] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_left = 1,
  field_operator = 2,
  field_right = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_operator] = "operator",
  [field_right] = "right",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 4,
  [9] = 5,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 14,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 22,
  [25] = 23,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 30,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 28,
  [47] = 31,
  [48] = 27,
  [49] = 32,
  [50] = 26,
  [51] = 33,
  [52] = 29,
  [53] = 53,
  [54] = 37,
  [55] = 53,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 58,
  [60] = 56,
  [61] = 57,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 69,
  [76] = 62,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '#', 20,
        '%', 12,
        '\'', 36,
        '.', 44,
        '=', 34,
        'E', 53,
        'I', 49,
        '[', 40,
        ']', 41,
        '{', 42,
        '|', 35,
        '}', 43,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '\'') ADVANCE(36);
      if (lookahead == 'E') ADVANCE(54);
      if (lookahead == 'I') ADVANCE(51);
      if (lookahead == '[') ADVANCE(39);
      if (lookahead == '{') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('.' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '\'') ADVANCE(36);
      if (lookahead == 'I') ADVANCE(51);
      if (lookahead == '[') ADVANCE(39);
      if (lookahead == '{') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('.' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '\'') ADVANCE(36);
      if (lookahead == '[') ADVANCE(39);
      if (lookahead == '{') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('.' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == 'E') ADVANCE(10);
      if (lookahead == '[') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 6:
      if (lookahead == '%') ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == 'D') ADVANCE(31);
      END_STATE();
    case 8:
      if (lookahead == 'E') ADVANCE(28);
      if (lookahead == 'I') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == 'F') ADVANCE(25);
      END_STATE();
    case 10:
      if (lookahead == 'L') ADVANCE(11);
      if (lookahead == 'N') ADVANCE(7);
      END_STATE();
    case 11:
      if (lookahead == 'S') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == ']') ADVANCE(22);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '#') ADVANCE(15);
      if (lookahead == '[') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '[') ADVANCE(20);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '#') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '[') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead != 0 &&
          lookahead != '[') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_content_token2);
      if (lookahead == '%') ADVANCE(21);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACK_PERCENT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PERCENT_RBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_IF);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_IF);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_ELSIF);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_ELSIF);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_ELSIF);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_ELSE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_ELSE);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_ELSE);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_END);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_END);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_END);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(60);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(61);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '#') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '%') ADVANCE(21);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D') ADVANCE(32);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E') ADVANCE(30);
      if (lookahead == 'I') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E') ADVANCE(29);
      if (lookahead == 'I') ADVANCE(52);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'F') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'F') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'F') ADVANCE(23);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'F') ADVANCE(26);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L') ADVANCE(55);
      if (lookahead == 'N') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L') ADVANCE(56);
      if (lookahead == 'N') ADVANCE(46);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S') ADVANCE(48);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_bare_string);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_comparison_operator);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_logical_operator);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 13},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 13},
  [7] = {.lex_state = 13},
  [8] = {.lex_state = 13},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 13},
  [15] = {.lex_state = 13},
  [16] = {.lex_state = 13},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 13},
  [27] = {.lex_state = 13},
  [28] = {.lex_state = 13},
  [29] = {.lex_state = 13},
  [30] = {.lex_state = 13},
  [31] = {.lex_state = 13},
  [32] = {.lex_state = 13},
  [33] = {.lex_state = 13},
  [34] = {.lex_state = 13},
  [35] = {.lex_state = 13},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 13},
  [47] = {.lex_state = 13},
  [48] = {.lex_state = 13},
  [49] = {.lex_state = 13},
  [50] = {.lex_state = 13},
  [51] = {.lex_state = 13},
  [52] = {.lex_state = 13},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 4},
  [67] = {.lex_state = 5},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 37},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 5},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_content_token2] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACK_PERCENT] = ACTIONS(1),
    [anon_sym_PERCENT_RBRACK] = ACTIONS(1),
    [anon_sym_IF] = ACTIONS(1),
    [anon_sym_ELSIF] = ACTIONS(1),
    [anon_sym_ELSE] = ACTIONS(1),
    [anon_sym_END] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comparison_operator] = ACTIONS(1),
    [sym_logical_operator] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(64),
    [sym__statement] = STATE(15),
    [sym_content] = STATE(15),
    [sym_directive] = STATE(15),
    [sym_simple_directive] = STATE(31),
    [sym_if_block] = STATE(31),
    [sym_if_directive] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_content_token1] = ACTIONS(7),
    [aux_sym_content_token2] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [anon_sym_LBRACK_PERCENT] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_IF,
    ACTIONS(15), 1,
      anon_sym_ELSIF,
    ACTIONS(17), 1,
      anon_sym_ELSE,
    ACTIONS(19), 1,
      anon_sym_END,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      sym_bare_string,
    STATE(21), 1,
      sym_variable,
    STATE(53), 7,
      sym__expression,
      sym_binary_expression,
      sym_assignment_expression,
      sym_filter_expression,
      sym_string,
      sym_array,
      sym_hash,
  [43] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_IF,
    ACTIONS(15), 1,
      anon_sym_ELSIF,
    ACTIONS(17), 1,
      anon_sym_ELSE,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      sym_bare_string,
    ACTIONS(31), 1,
      anon_sym_END,
    STATE(21), 1,
      sym_variable,
    STATE(53), 7,
      sym__expression,
      sym_binary_expression,
      sym_assignment_expression,
      sym_filter_expression,
      sym_string,
      sym_array,
      sym_hash,
  [86] = 9,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_LBRACK_PERCENT,
    STATE(4), 1,
      sym_if_directive,
    STATE(48), 1,
      sym_end_directive,
    STATE(58), 1,
      sym_else_directive,
    ACTIONS(33), 2,
      aux_sym_content_token1,
      aux_sym_content_token2,
    STATE(24), 2,
      sym_elsif_directive,
      aux_sym_if_block_repeat1,
    STATE(47), 2,
      sym_simple_directive,
      sym_if_block,
    STATE(7), 4,
      sym__statement,
      sym_content,
      sym_directive,
      aux_sym_source_file_repeat1,
  [120] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_IF,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_bare_string,
    STATE(21), 1,
      sym_variable,
    STATE(55), 7,
      sym__expression,
      sym_binary_expression,
      sym_assignment_expression,
      sym_filter_expression,
      sym_string,
      sym_array,
      sym_hash,
  [154] = 9,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(39), 1,
      anon_sym_LBRACK_PERCENT,
    STATE(4), 1,
      sym_if_directive,
    STATE(33), 1,
      sym_end_directive,
    STATE(56), 1,
      sym_else_directive,
    ACTIONS(33), 2,
      aux_sym_content_token1,
      aux_sym_content_token2,
    STATE(25), 2,
      sym_elsif_directive,
      aux_sym_if_block_repeat1,
    STATE(47), 2,
      sym_simple_directive,
      sym_if_block,
    STATE(16), 4,
      sym__statement,
      sym_content,
      sym_directive,
      aux_sym_source_file_repeat1,
  [188] = 9,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_LBRACK_PERCENT,
    STATE(4), 1,
      sym_if_directive,
    STATE(51), 1,
      sym_end_directive,
    STATE(60), 1,
      sym_else_directive,
    ACTIONS(33), 2,
      aux_sym_content_token1,
      aux_sym_content_token2,
    STATE(23), 2,
      sym_elsif_directive,
      aux_sym_if_block_repeat1,
    STATE(47), 2,
      sym_simple_directive,
      sym_if_block,
    STATE(16), 4,
      sym__statement,
      sym_content,
      sym_directive,
      aux_sym_source_file_repeat1,
  [222] = 9,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(39), 1,
      anon_sym_LBRACK_PERCENT,
    STATE(4), 1,
      sym_if_directive,
    STATE(27), 1,
      sym_end_directive,
    STATE(59), 1,
      sym_else_directive,
    ACTIONS(33), 2,
      aux_sym_content_token1,
      aux_sym_content_token2,
    STATE(22), 2,
      sym_elsif_directive,
      aux_sym_if_block_repeat1,
    STATE(47), 2,
      sym_simple_directive,
      sym_if_block,
    STATE(6), 4,
      sym__statement,
      sym_content,
      sym_directive,
      aux_sym_source_file_repeat1,
  [256] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_IF,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      sym_bare_string,
    STATE(21), 1,
      sym_variable,
    STATE(53), 7,
      sym__expression,
      sym_binary_expression,
      sym_assignment_expression,
      sym_filter_expression,
      sym_string,
      sym_array,
      sym_hash,
  [290] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(41), 1,
      sym_bare_string,
    STATE(21), 1,
      sym_variable,
    STATE(42), 7,
      sym__expression,
      sym_binary_expression,
      sym_assignment_expression,
      sym_filter_expression,
      sym_string,
      sym_array,
      sym_hash,
  [321] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(43), 1,
      sym_bare_string,
    STATE(21), 1,
      sym_variable,
    STATE(36), 7,
      sym__expression,
      sym_binary_expression,
      sym_assignment_expression,
      sym_filter_expression,
      sym_string,
      sym_array,
      sym_hash,
  [352] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(45), 1,
      sym_bare_string,
    STATE(21), 1,
      sym_variable,
    STATE(43), 7,
      sym__expression,
      sym_binary_expression,
      sym_assignment_expression,
      sym_filter_expression,
      sym_string,
      sym_array,
      sym_hash,
  [383] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(47), 1,
      sym_bare_string,
    STATE(21), 1,
      sym_variable,
    STATE(45), 7,
      sym__expression,
      sym_binary_expression,
      sym_assignment_expression,
      sym_filter_expression,
      sym_string,
      sym_array,
      sym_hash,
  [414] = 7,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 1,
      anon_sym_LBRACK_PERCENT,
    STATE(8), 1,
      sym_if_directive,
    ACTIONS(51), 2,
      aux_sym_content_token1,
      aux_sym_content_token2,
    STATE(31), 2,
      sym_simple_directive,
      sym_if_block,
    STATE(14), 4,
      sym__statement,
      sym_content,
      sym_directive,
      aux_sym_source_file_repeat1,
  [441] = 7,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LBRACK_PERCENT,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      sym_if_directive,
    ACTIONS(7), 2,
      aux_sym_content_token1,
      aux_sym_content_token2,
    STATE(31), 2,
      sym_simple_directive,
      sym_if_block,
    STATE(14), 4,
      sym__statement,
      sym_content,
      sym_directive,
      aux_sym_source_file_repeat1,
  [468] = 6,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_LBRACK_PERCENT,
    STATE(4), 1,
      sym_if_directive,
    ACTIONS(59), 2,
      aux_sym_content_token1,
      aux_sym_content_token2,
    STATE(47), 2,
      sym_simple_directive,
      sym_if_block,
    STATE(16), 4,
      sym__statement,
      sym_content,
      sym_directive,
      aux_sym_source_file_repeat1,
  [492] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_DOT,
    STATE(19), 1,
      aux_sym_variable_repeat1,
    ACTIONS(67), 2,
      anon_sym_EQ,
      anon_sym_PIPE,
    ACTIONS(65), 3,
      anon_sym_PERCENT_RBRACK,
      sym_comparison_operator,
      sym_logical_operator,
  [511] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_DOT,
    STATE(17), 1,
      aux_sym_variable_repeat1,
    ACTIONS(73), 2,
      anon_sym_EQ,
      anon_sym_PIPE,
    ACTIONS(71), 3,
      anon_sym_PERCENT_RBRACK,
      sym_comparison_operator,
      sym_logical_operator,
  [530] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_DOT,
    STATE(19), 1,
      aux_sym_variable_repeat1,
    ACTIONS(77), 2,
      anon_sym_EQ,
      anon_sym_PIPE,
    ACTIONS(75), 3,
      anon_sym_PERCENT_RBRACK,
      sym_comparison_operator,
      sym_logical_operator,
  [549] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 2,
      anon_sym_EQ,
      anon_sym_PIPE,
    ACTIONS(75), 4,
      anon_sym_PERCENT_RBRACK,
      anon_sym_DOT,
      sym_comparison_operator,
      sym_logical_operator,
  [563] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_EQ,
    ACTIONS(86), 1,
      anon_sym_PIPE,
    ACTIONS(82), 3,
      anon_sym_PERCENT_RBRACK,
      sym_comparison_operator,
      sym_logical_operator,
  [578] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_LBRACK_PERCENT,
    STATE(33), 1,
      sym_end_directive,
    STATE(56), 1,
      sym_else_directive,
    STATE(38), 2,
      sym_elsif_directive,
      aux_sym_if_block_repeat1,
  [595] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_LBRACK_PERCENT,
    STATE(49), 1,
      sym_end_directive,
    STATE(61), 1,
      sym_else_directive,
    STATE(38), 2,
      sym_elsif_directive,
      aux_sym_if_block_repeat1,
  [612] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_LBRACK_PERCENT,
    STATE(51), 1,
      sym_end_directive,
    STATE(60), 1,
      sym_else_directive,
    STATE(38), 2,
      sym_elsif_directive,
      aux_sym_if_block_repeat1,
  [629] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_LBRACK_PERCENT,
    STATE(32), 1,
      sym_end_directive,
    STATE(57), 1,
      sym_else_directive,
    STATE(38), 2,
      sym_elsif_directive,
      aux_sym_if_block_repeat1,
  [646] = 3,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(94), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_LBRACK_PERCENT,
  [658] = 3,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    ACTIONS(98), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_LBRACK_PERCENT,
  [670] = 3,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(100), 1,
      ts_builtin_sym_end,
    ACTIONS(102), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_LBRACK_PERCENT,
  [682] = 3,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(106), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_LBRACK_PERCENT,
  [694] = 3,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
    ACTIONS(110), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_LBRACK_PERCENT,
  [706] = 3,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_LBRACK_PERCENT,
  [718] = 3,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
    ACTIONS(118), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_LBRACK_PERCENT,
  [730] = 3,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
    ACTIONS(122), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_LBRACK_PERCENT,
  [742] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(110), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_LBRACK_PERCENT,
  [751] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(124), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_LBRACK_PERCENT,
  [760] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_PERCENT_RBRACK,
    ACTIONS(128), 2,
      sym_comparison_operator,
      sym_logical_operator,
  [771] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_ELSIF,
    ACTIONS(132), 1,
      anon_sym_ELSE,
    ACTIONS(134), 1,
      anon_sym_END,
  [784] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_LBRACK_PERCENT,
    STATE(38), 2,
      sym_elsif_directive,
      aux_sym_if_block_repeat1,
  [795] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 3,
      anon_sym_PERCENT_RBRACK,
      sym_comparison_operator,
      sym_logical_operator,
  [804] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 3,
      anon_sym_PERCENT_RBRACK,
      sym_comparison_operator,
      sym_logical_operator,
  [813] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 3,
      anon_sym_PERCENT_RBRACK,
      sym_comparison_operator,
      sym_logical_operator,
  [822] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 3,
      anon_sym_PERCENT_RBRACK,
      sym_comparison_operator,
      sym_logical_operator,
  [831] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_PERCENT_RBRACK,
    ACTIONS(128), 2,
      sym_comparison_operator,
      sym_logical_operator,
  [842] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 3,
      anon_sym_PERCENT_RBRACK,
      sym_comparison_operator,
      sym_logical_operator,
  [851] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_PERCENT_RBRACK,
    ACTIONS(128), 2,
      sym_comparison_operator,
      sym_logical_operator,
  [862] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(102), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_LBRACK_PERCENT,
  [871] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(114), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_LBRACK_PERCENT,
  [880] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(98), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_LBRACK_PERCENT,
  [889] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(118), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_LBRACK_PERCENT,
  [898] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(94), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_LBRACK_PERCENT,
  [907] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(122), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_LBRACK_PERCENT,
  [916] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(106), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_LBRACK_PERCENT,
  [925] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_PERCENT_RBRACK,
    ACTIONS(128), 2,
      sym_comparison_operator,
      sym_logical_operator,
  [936] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_ELSIF,
    ACTIONS(132), 1,
      anon_sym_ELSE,
    ACTIONS(155), 1,
      anon_sym_END,
  [949] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_PERCENT_RBRACK,
    ACTIONS(128), 2,
      sym_comparison_operator,
      sym_logical_operator,
  [960] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_LBRACK_PERCENT,
    STATE(32), 1,
      sym_end_directive,
  [970] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_LBRACK_PERCENT,
    STATE(30), 1,
      sym_end_directive,
  [980] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_LBRACK_PERCENT,
    STATE(51), 1,
      sym_end_directive,
  [990] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_LBRACK_PERCENT,
    STATE(33), 1,
      sym_end_directive,
  [1000] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_LBRACK_PERCENT,
    STATE(49), 1,
      sym_end_directive,
  [1010] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_LBRACK_PERCENT,
    STATE(34), 1,
      sym_end_directive,
  [1020] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_END,
  [1027] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_RBRACE,
  [1034] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      ts_builtin_sym_end,
  [1041] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_LBRACK_PERCENT,
  [1048] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_ELSIF,
  [1055] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      sym_identifier,
  [1062] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_LBRACK_PERCENT,
  [1069] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_PERCENT_RBRACK,
  [1076] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(175), 1,
      aux_sym_string_token1,
  [1083] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_RBRACK,
  [1090] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_PERCENT_RBRACK,
  [1097] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_SQUOTE,
  [1104] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      sym_identifier,
  [1111] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_PERCENT_RBRACK,
  [1118] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_END,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 43,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 120,
  [SMALL_STATE(6)] = 154,
  [SMALL_STATE(7)] = 188,
  [SMALL_STATE(8)] = 222,
  [SMALL_STATE(9)] = 256,
  [SMALL_STATE(10)] = 290,
  [SMALL_STATE(11)] = 321,
  [SMALL_STATE(12)] = 352,
  [SMALL_STATE(13)] = 383,
  [SMALL_STATE(14)] = 414,
  [SMALL_STATE(15)] = 441,
  [SMALL_STATE(16)] = 468,
  [SMALL_STATE(17)] = 492,
  [SMALL_STATE(18)] = 511,
  [SMALL_STATE(19)] = 530,
  [SMALL_STATE(20)] = 549,
  [SMALL_STATE(21)] = 563,
  [SMALL_STATE(22)] = 578,
  [SMALL_STATE(23)] = 595,
  [SMALL_STATE(24)] = 612,
  [SMALL_STATE(25)] = 629,
  [SMALL_STATE(26)] = 646,
  [SMALL_STATE(27)] = 658,
  [SMALL_STATE(28)] = 670,
  [SMALL_STATE(29)] = 682,
  [SMALL_STATE(30)] = 694,
  [SMALL_STATE(31)] = 706,
  [SMALL_STATE(32)] = 718,
  [SMALL_STATE(33)] = 730,
  [SMALL_STATE(34)] = 742,
  [SMALL_STATE(35)] = 751,
  [SMALL_STATE(36)] = 760,
  [SMALL_STATE(37)] = 771,
  [SMALL_STATE(38)] = 784,
  [SMALL_STATE(39)] = 795,
  [SMALL_STATE(40)] = 804,
  [SMALL_STATE(41)] = 813,
  [SMALL_STATE(42)] = 822,
  [SMALL_STATE(43)] = 831,
  [SMALL_STATE(44)] = 842,
  [SMALL_STATE(45)] = 851,
  [SMALL_STATE(46)] = 862,
  [SMALL_STATE(47)] = 871,
  [SMALL_STATE(48)] = 880,
  [SMALL_STATE(49)] = 889,
  [SMALL_STATE(50)] = 898,
  [SMALL_STATE(51)] = 907,
  [SMALL_STATE(52)] = 916,
  [SMALL_STATE(53)] = 925,
  [SMALL_STATE(54)] = 936,
  [SMALL_STATE(55)] = 949,
  [SMALL_STATE(56)] = 960,
  [SMALL_STATE(57)] = 970,
  [SMALL_STATE(58)] = 980,
  [SMALL_STATE(59)] = 990,
  [SMALL_STATE(60)] = 1000,
  [SMALL_STATE(61)] = 1010,
  [SMALL_STATE(62)] = 1020,
  [SMALL_STATE(63)] = 1027,
  [SMALL_STATE(64)] = 1034,
  [SMALL_STATE(65)] = 1041,
  [SMALL_STATE(66)] = 1048,
  [SMALL_STATE(67)] = 1055,
  [SMALL_STATE(68)] = 1062,
  [SMALL_STATE(69)] = 1069,
  [SMALL_STATE(70)] = 1076,
  [SMALL_STATE(71)] = 1083,
  [SMALL_STATE(72)] = 1090,
  [SMALL_STATE(73)] = 1097,
  [SMALL_STATE(74)] = 1104,
  [SMALL_STATE(75)] = 1111,
  [SMALL_STATE(76)] = 1118,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_variable_repeat1, 2, 0, 0),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_directive, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_simple_directive, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_block, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_block, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_directive, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_directive, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_block, 5, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_block, 5, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_block, 4, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_block, 4, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_block, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_block, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_directive, 4, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_block_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_expression, 3, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter_expression, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [165] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_directive, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elsif_directive, 4, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_template_toolkit(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "template_toolkit",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
